/**
*
Copyright (c) 2014-15 Kavindra Dubey - kavindra.dubey@gmail.com [personal site - devtrip.com]. devtripVideo v1.0 <https://github.com/kavindraD/devtripVideo/blob/master/simple/Html5VideoPlayer/eventHandlers/build/devtripVideo.js> 
	is released under the MIT License <http://opensource.org/licenses/MIT> 

Except as contained in this notice, the name(s) of the above copyright holders shall not be used in advertising or otherwise to promote the sale, use or other dealings in this Software without prior written authorization.

The end-user documentation included with the redistribution, if any, must include the following acknowledgment: "This product includes software developed by The devtripVideo Project, (http://www.devtrip.com/) and its contributors", in the same place and form as other third-party acknowledgments. Alternately, this acknowledgment may appear in the software itself, in the same form and location as other such third-party acknowledgments.
*
**/
var devtripVideo=function(){function h(a,c){var b=a.canPlayType(c);if("maybe"==b)return c;if(""==b)return""}function f(a,c,b,d){window.addEventListener?a.addEventListener(c,b,d):document.attachEvent?a.attachEvent("on"+c,b):a["on"+c]=b}function e(a,c,b,d){window.removeEventListener?a.removeEventListener(c,b,d):document.detachEvent?a.detachEvent("on"+c,b):a["on"+c]=null}function k(a){switch(a.target.error.code){case a.target.error.MEDIA_ERR_ABORTED:alert("You aborted the video playback.");break;case a.target.error.MEDIA_ERR_NETWORK:alert("A network error caused the video download to fail part-way.");
break;case a.target.error.MEDIA_ERR_DECODE:alert("The video playback was aborted due to a corruption problem or because the video used features your browser did not support.");break;case a.target.error.MEDIA_ERR_SRC_NOT_SUPPORTED:alert("The video could not be loaded, either because the server or network failed or because the format is not supported.");break;default:alert("An unknown error occurred.")}l.call()}function m(a){n.call()}function p(a){q.call()}function r(a){s.call()}function t(a){u.call()}
function v(a){w.call()}function x(a){y.call()}function z(a){A.call()}function B(a){C.call()}function D(a){E.call()}function F(a){G.call()}function H(a){I.call()}function J(a){K.call()}function L(a){M.call()}function N(a){O.call()}function P(a,c,b){var d=document.createElement("script");d.type="text/javascript";d.id="swfLoader";d.readyState?d.onreadystatechange=function(){if("loaded"==d.readyState||"complete"==d.readyState)d.onreadystatechange=null,c()}:d.onload=function(){c()};d.src=a;document.getElementsByTagName("head")[0].appendChild(d)}
function Q(a){P(g+"swfobject.js",function(){var c={};c.DT_width=a.width;c.DT_height=a.height;c.DT_video=a.video+".mp4";c.DT_autoplay=a.autoplay;c.DT_videoImage=a.videoImage;c.DT_assetsPath=g;(new swfobject).embedSWF(g+"player.swf",a.containerId,a.width,a.height,"9.0.0",g+"expressInstall.swf",c)})}var g="assets/",l=function(){},n=function(){},q=function(){},s=function(){},u=function(){},w=function(){},y=function(){},A=function(){},C=function(){},E=function(){},G=function(){},I=function(){},K=function(){},
M=function(){},O=function(){};return{init:function(a){if(document.createElement("video").canPlayType){var c=document.getElementById(a.containerId),b=document.createElement("video");b.id="videoplayer";b.width=a.width;b.height=a.height;var d=g+a.video;ogg="video/ogg";webm="video/webm";var e=".dt";"video/mp4"==h(b,"video/mp4")?e=".mp4":h(b,webm)==webm?e=".webm":h(b,ogg)==ogg&&(e=".ogg");b.src=d+e;ogg="video/ogg";webm="video/webm";d="video/dt";"video/mp4"==h(b,"video/mp4")?d="video/mp4":h(b,webm)==webm?
d=webm:h(b,ogg)==ogg&&(d=ogg);b.type=d;b.autoplay=a.autoplay;b.controls=!0;b.muted=!0;b.poster=g+a.videoImage;c.appendChild(b);a=document.getElementById("videoplayer");f(a,"error",k,!0);f(a,"loadedmetadata",m,!1);f(a,"timeupdate",p,!1);f(a,"pause",r,!1);f(a,"playing",t,!1);f(a,"volumechange",v,!1);f(a,"loadstart",x,!1);f(a,"loadeddata",z,!1);f(a,"ended",B,!1);f(a,"emptied",D,!1);f(a,"stalled",F,!1);f(a,"waiting",H,!1);f(a,"progress",J,!1);f(a,"durationchange",L,!1);f(a,"canplaythrough",N,!1);addCallbackFunction("videoplayer")}else Q(a)},
dispose:function(){var a=document.getElementById("videoplayer");e(a,"error",k,!0);e(a,"loadedmetadata",m,!1);e(a,"timeupdate",p,!1);e(a,"pause",r,!1);e(a,"playing",t,!1);e(a,"volumechange",v,!1);e(a,"loadstart",x,!1);e(a,"loadeddata",z,!1);e(a,"ended",B,!1);e(a,"emptied",D,!1);e(a,"stalled",F,!1);e(a,"waiting",H,!1);e(a,"progress",J,!1);e(a,"durationchange",L,!1);e(a,"canplaythrough",N,!1)},setPath:function(a){g=a},cllback_errorHandler:function(a){l=a},cllback_loadedmetadataHandler:function(a){n=
a},cllback_timeupdateHandler:function(a){q=a},cllback_pauseHandler:function(a){s=a},cllback_playingHandler:function(a){u=a},cllback_volumechangeHandler:function(a){w=a},cllback_loadstartHandler:function(a){y=a},cllback_loadeddataHandler:function(a){A=a},cllback_endedHandler:function(a){C=a},cllback_emptiedHandler:function(a){E=a},cllback_stalledHandler:function(a){G=a},cllback_waitingHandler:function(a){I=a},cllback_progressHandler:function(a){K=a},cllback_durationchangeHandler:function(a){M=a},cllback_canplaythroughHandler:function(a){O=
a}}};
